const apartmentData = {
   "P1": {
      "05": {
         "01": {
            "code": "P1-05-01",
            "type": "Studio",
            "area": 31.53,
            "price": "",
            "floor": 5,
            "directionLabel": "Hướng Đông Nam",
            "direction": "dong-nam.jpg",
            "view": "bien.jpg",
            "viewLabel": "Biển",
            "position": 1,
         },
         "02": {
            "code": "P1-05-02",
            "type": "Studio",
            "area": 32.04,
            "price": "",
            "floor": 5,
            "directionLabel": "Hướng Đông Nam",
            "direction": "dong-nam.jpg",
            "view": "bien.jpg",
            "viewLabel": "Biển",
            "position": 1,
         },
         "03": {
            "code": "P1-05-03",
            "type": "Studio",
            "area": 32.04,
            "price": "",
            "floor": 5,
            "directionLabel": "Hướng Đông Nam",
            "direction": "dong-nam.jpg",
            "view": "bien.jpg",
            "viewLabel": "Biển",
            "position": 1,
         },
         "03A": {
            "code": "P1-05-03A",
            "type": "Studio",
            "area": 32.04,
            "price": "",
            "floor": 5,
            "directionLabel": "Hướng Đông Nam",
            "direction": "dong-nam.jpg",
            "view": "bien.jpg",
            "viewLabel": "Biển",
            "position": 1,
         },
         "05": {
            "code": "P1-05-05",
            "type": "Studio",
            "area": 32.04,
            "price": "",
            "floor": 5,
            "directionLabel": "Hướng Đông Nam",
            "direction": "dong-nam.jpg",
            "view": "bien.jpg",
            "viewLabel": "Biển",
            "position": 1,
         },
         "06": {
            "code": "P1-05-06",
            "type": "Studio",
            "area": 32.04,
            "price": "",
            "floor": 5,
            "directionLabel": "Hướng Đông Nam",
            "direction": "dong-nam.jpg",
            "view": "bien.jpg",
            "viewLabel": "Biển",
            "position": 1,
         },
         "07": {
            "code": "P1-05-07",
            "type": "Studio",
            "area": 32.04,
            "price": "",
            "floor": 5,
            "directionLabel": "Hướng Đông Nam",
            "direction": "dong-nam.jpg",
            "view": "bien.jpg",
            "viewLabel": "Biển",
            "position": 1,
         },
         "08": {
            "code": "P1-05-08",
            "type": "Studio",
            "area": 31.27,
            "price": "",
            "floor": 5,
            "directionLabel": "Hướng Đông Nam",
            "direction": "dong-nam.jpg",
            "view": "bien.jpg",
            "viewLabel": "Biển",
            "position": 1,
         },
         "09": {
            "code": "P1-05-09",
            "type": "Studio",
            "area": 31.21,
            "price": "",
            "floor": 5,
            "directionLabel": "Hướng Đông Nam",
            "direction": "dong-nam.jpg",
            "view": "bien.jpg",
            "viewLabel": "Biển",
            "position": 1,
         },
         "10": {
            "code": "P1-05-10",
            "type": "Studio",
            "area": 32.04,
            "price": "",
            "floor": 5,
            "directionLabel": "Hướng Đông Nam",
            "direction": "dong-nam.jpg",
            "view": "bien.jpg",
            "viewLabel": "Biển",
            "position": 1,
         },
         "11": {
            "code": "P1-05-11",
            "type": "Studio",
            "area": 32.04,
            "price": "",
            "floor": 5,
            "directionLabel": "Hướng Đông Nam",
            "direction": "dong-nam.jpg",
            "view": "bien.jpg",
            "viewLabel": "Biển",
            "position": 1,
         },
         "12": {
            "code": "P1-05-12",
            "type": "2PN",
            "area": 59.24,
            "price": "",
            "floor": 5,
            "directionLabel": "Hướng Đông Nam",
            "direction": "dong-nam.jpg",
            "view": "bien.jpg",
            "viewLabel": "Biển",
            "position": 1,
         },
         "12A": {
            "code": "P1-05-12A",
            "type": "Studio",
            "area": 40.15,
            "price": "",
            "floor": 5,
            "directionLabel": "Hướng Đông Nam",
            "direction": "dong-nam.jpg",
            "view": "bien.jpg",
            "viewLabel": "Biển",
            "position": 1,
         },
         "14": {
            "code": "P1-05-14",
            "type": "Studio",
            "area": 40.15,
            "price": "",
            "floor": 5,
            "directionLabel": "Hướng Đông Nam",
            "direction": "dong-nam.jpg",
            "view": "bien.jpg",
            "viewLabel": "Biển",
            "position": 1,
         },
         "15": {
            "code": "P1-05-15",
            "type": "3PN",
            "area": 169.39,
            "price": "",
            "floor": 5,
            "directionLabel": "Hướng Nam - Đông Nam",
            "direction": "nam-dong-nam.jpg",
            "view": "bien-vinhhalong.jpg",
            "viewLabel": "Biển - Vịnh Hạ Long",
            "position": 1,
         },
         "16": {
            "code": "P1-05-16",
            "type": "2PN",
            "area": 100.73,
            "price": "",
            "floor": 5,
            "directionLabel": "Hướng Tây - Đông Nam",
            "direction": "tay-dong-nam.jpg",
            "view": "bien-halongxanh-vinhhalong.jpg",
            "viewLabel": "Biển - Hạ Long Xanh <br/> - Vịnh Hạ Long",
            "position": 1
         },
         "17": {
            "code": "P1-05-17",
            "type": "Studio",
            "area": 32.43,
            "price": "",
            "floor": 5,
            "directionLabel": "Hướng Tây",
            "direction": "tay.jpg",
            "view": "bien-halongxanh.jpg",
            "viewLabel": "Biển - Hạ Long Xanh",
            "position": 3
         },
         "18": {
            "code": "P1-05-18",
            "type": "2PN",
            "area": 59.68,
            "price": "",
            "floor": 5,
            "directionLabel": "Hướng Tây",
            "direction": "tay.jpg",
            "view": "bien-halongxanh.jpg",
            "viewLabel": "Biển - Hạ Long Xanh",
            "position": 3
         },
         "19": {
            "code": "P1-05-19",
            "type": "Studio",
            "area": 42.88,
            "price": "",
            "floor": 5,
            "directionLabel": "Hướng Tây",
            "direction": "tay.jpg",
            "view": "bien-halongxanh.jpg",
            "viewLabel": "Biển - Hạ Long Xanh",
            "position": 3
         },
         "20": {
            "code": "P1-05-20",
            "type": "Studio",
            "area": 32.32,
            "price": "",
            "floor": 5,
            "directionLabel": "Hướng Tây",
            "direction": "tay.jpg",
            "view": "bien-halongxanh.jpg",
            "viewLabel": "Biển - Hạ Long Xanh",
            "position": 3
         },
         "21": {
            "code": "P1-05-21",
            "type": "Studio",
            "area": 32.32,
            "price": "",
            "floor": 5,
            "directionLabel": "Hướng Tây",
            "direction": "tay.jpg",
            "view": "bien-halongxanh.jpg",
            "viewLabel": "Biển - Hạ Long Xanh",
            "position": 3
         },
         "22": {
            "code": "P1-05-22",
            "type": "Studio",
            "area": 32.32,
            "price": "",
            "floor": 5,
            "directionLabel": "Hướng Tây",
            "direction": "tay.jpg",
            "view": "bien-halongxanh.jpg",
            "viewLabel": "Biển - Hạ Long Xanh",
            "position": 3
         },
         "23": {
            "code": "P1-05-23",
            "type": "Studio",
            "area": 32.32,
            "price": "",
            "floor": 5,
            "directionLabel": "Hướng Tây",
            "direction": "tay.jpg",
            "view": "bien-halongxanh.jpg",
            "viewLabel": "Biển - Hạ Long Xanh",
            "position": 3
         },
         "24": {
            "code": "P1-05-24",
            "type": "Studio",
            "area": 32.32,
            "price": "",
            "floor": 5,
            "directionLabel": "Hướng Tây",
            "direction": "tay.jpg",
            "view": "bien-halongxanh.jpg",
            "viewLabel": "Biển - Hạ Long Xanh",
            "position": 3
         },
         "25": {
            "code": "P1-05-25",
            "type": "Studio",
            "area": 32.32,
            "price": "",
            "floor": 5,
            "directionLabel": "Hướng Tây",
            "direction": "tay.jpg",
            "view": "bien-halongxanh.jpg",
            "viewLabel": "Biển - Hạ Long Xanh",
            "position": 3
         },
         "26": {
            "code": "P1-05-26",
            "type": "Studio",
            "area": 33.66,
            "price": "",
            "floor": 5,
            "directionLabel": "Hướng Tây",
            "direction": "tay.jpg",
            "view": "bien-halongxanh.jpg",
            "viewLabel": "Biển - Hạ Long Xanh",
            "position": 3
         }
      },
      "06": {
         "01": {
            "code": "P1-06-01",
            "type": "Studio",
            "area": 31.47,
            "price": null,
            "floor": 7,
            "directionLabel": "Hướng Đông Nam",
            "direction": "dong-nam.jpg",
            "view": "bien.jpg",
            "viewLabel": "Biển",
            "position": 1
         },
         "02": {
            "code": "P1-06-02",
            "type": "Studio",
            "area": 32.04,
            "price": null,
            "floor": 7,
            "directionLabel": "Hướng Đông Nam",
            "direction": "dong-nam.jpg",
            "view": "bien.jpg",
            "viewLabel": "Biển",
            "position": 1
         },
         "03": {
            "code": "P1-06-03",
            "type": "Studio",
            "area": 31.98,
            "price": null,
            "floor": 7,
            "directionLabel": "Hướng Đông Nam",
            "direction": "dong-nam.jpg",
            "view": "bien.jpg",
            "viewLabel": "Biển",
            "position": 1
         },
         "03A": {
            "code": "P1-06-03A",
            "type": "Studio",
            "area": 31.01,
            "price": null,
            "floor": 7,
            "directionLabel": "Hướng Đông Nam",
            "direction": "dong-nam.jpg",
            "view": "bien.jpg",
            "viewLabel": "Biển",
            "position": 1
         },
         "05": {
            "code": "P1-06-05",
            "type": "Studio",
            "area": 31.01,
            "price": null,
            "floor": 7,
            "directionLabel": "Hướng Đông Nam",
            "direction": "dong-nam.jpg",
            "view": "bien.jpg",
            "viewLabel": "Biển",
            "position": 1
         },
         "06": {
            "code": "P1-06-06",
            "type": "Studio",
            "area": 31.94,
            "price": null,
            "floor": 7,
            "directionLabel": "Hướng Đông Nam",
            "direction": "dong-nam.jpg",
            "view": "bien.jpg",
            "viewLabel": "Biển",
            "position": 1
         },
         "07": {
            "code": "P1-06-07",
            "type": "Studio",
            "area": 31.94,
            "price": null,
            "floor": 7,
            "directionLabel": "Hướng Đông Nam",
            "direction": "dong-nam.jpg",
            "view": "bien.jpg",
            "viewLabel": "Biển",
            "position": 1
         },
         "08": {
            "code": "P1-06-08",
            "type": "Studio",
            "area": 31.01,
            "price": null,
            "floor": 7,
            "directionLabel": "Hướng Đông Nam",
            "direction": "dong-nam.jpg",
            "view": "bien.jpg",
            "viewLabel": "Biển",
            "position": 1
         },
         "09": {
            "code": "P1-06-09",
            "type": "Studio",
            "area": 31.94,
            "price": null,
            "floor": 7,
            "directionLabel": "Hướng Đông Nam",
            "direction": "dong-nam.jpg",
            "view": "bien.jpg",
            "viewLabel": "Biển",
            "position": 1
         },
         "10": {
            "code": "P1-06-10",
            "type": "Studio",
            "area": 31.98,
            "price": null,
            "floor": 7,
            "directionLabel": "Hướng Đông Nam",
            "direction": "dong-nam.jpg",
            "view": "bien.jpg",
            "viewLabel": "Biển",
            "position": 1
         },
         "11": {
            "code": "P1-06-11",
            "type": "Studio",
            "area": 31.98,
            "price": null,
            "floor": 7,
            "directionLabel": "Hướng Đông Nam",
            "direction": "dong-nam.jpg",
            "view": "bien.jpg",
            "viewLabel": "Biển",
            "position": 1
         },
         "12": {
            "code": "P1-06-12",
            "type": "2PN",
            "area": 57.34,
            "price": null,
            "floor": 7,
            "directionLabel": "Hướng Đông Nam",
            "direction": "dong-nam.jpg",
            "view": "bien.jpg",
            "viewLabel": "Biển",
            "position": 1
         },
         "12A": {
            "code": "P1-06-12A",
            "type": "Studio",
            "area": 31.94,
            "price": null,
            "floor": 7,
            "directionLabel": "Hướng Đông Nam",
            "direction": "dong-nam.jpg",
            "view": "bien.jpg",
            "viewLabel": "Biển",
            "position": 1
         },
         "14": {
            "code": "P1-06-14",
            "type": "Studio",
            "area": 32.00,
            "price": null,
            "floor": 7,
            "directionLabel": "Hướng Đông Nam",
            "direction": "dong-nam.jpg",
            "view": "bien.jpg",
            "viewLabel": "Biển",
            "position": 1
         },
         "15": {
            "code": "P1-06-15",
            "type": "3PN",
            "area": 105.94,
            "price": null,
            "floor": 7,
            "directionLabel": "Hướng Nam - Đông Nam",
            "direction": "nam-dong-nam.jpg",
            "view": "bien-vinhhalong.jpg",
            "viewLabel": "Biển - Vịnh Hạ Long",
            "position": 1
         },
         "16": {
            "code": "P1-06-16",
            "type": "2PN",
            "area": 72.05,
            "price": null,
            "floor": 7,
            "directionLabel": "Hướng Tây Nam",
            "direction": "tay-nam.jpg",
            "view": "bien-halongxanh-vinhhalong.jpg",
            "viewLabel": "Biển - Hạ Long Xanh <br/> - Vịnh Hạ Long",
            "position": 1
         },
         "17": {
            "code": "P1-06-17",
            "type": "Studio",
            "area": 31.39,
            "price": null,
            "floor": 7,
            "directionLabel": "Hướng Tây",
            "direction": "tay.jpg",
            "view": "bien-halongxanh.jpg",
            "viewLabel": "Biển - Hạ Long Xanh",
            "position": 3
         },
         "18": {
            "code": "P1-06-18",
            "type": "2PN",
            "area": 58.40,
            "price": null,
            "floor": 7,
            "directionLabel": "Hướng Tây",
            "direction": "tay.jpg",
            "view": "bien-halongxanh.jpg",
            "viewLabel": "Biển - Hạ Long Xanh",
            "position": 3
         },
         "19": {
            "code": "P1-06-19",
            "type": "Studio",
            "area": 42.88,
            "price": null,
            "floor": 7,
            "directionLabel": "Hướng Tây",
            "direction": "tay.jpg",
            "view": "bien-halongxanh.jpg",
            "viewLabel": "Biển - Hạ Long Xanh",
            "position": 3
         },
         "20": {
            "code": "P1-06-20",
            "type": "Studio",
            "area": 32.26,
            "price": null,
            "floor": 7,
            "directionLabel": "Hướng Tây",
            "direction": "tay.jpg",
            "view": "bien-halongxanh.jpg",
            "viewLabel": "Biển - Hạ Long Xanh",
            "position": 3
         },
         "21": {
            "code": "P1-06-21",
            "type": "Studio",
            "area": 31.29,
            "price": null,
            "floor": 7,
            "directionLabel": "Hướng Tây",
            "direction": "tay.jpg",
            "view": "bien-halongxanh.jpg",
            "viewLabel": "Biển - Hạ Long Xanh",
            "position": 3
         },
         "22": {
            "code": "P1-06-22",
            "type": "Studio",
            "area": 31.29,
            "price": null,
            "floor": 7,
            "directionLabel": "Hướng Tây",
            "direction": "tay.jpg",
            "view": "bien-halongxanh.jpg",
            "viewLabel": "Biển - Hạ Long Xanh",
            "position": 3
         },
         "23": {
            "code": "P1-06-23",
            "type": "Studio",
            "area": 32.26,
            "price": null,
            "floor": 7,
            "directionLabel": "Hướng Tây",
            "direction": "tay.jpg",
            "view": "bien-halongxanh.jpg",
            "viewLabel": "Biển - Hạ Long Xanh",
            "position": 3
         },
         "24": {
            "code": "P1-06-24",
            "type": "Studio",
            "area": 32.26,
            "price": null,
            "floor": 7,
            "directionLabel": "Hướng Tây",
            "direction": "tay.jpg",
            "view": "bien-halongxanh.jpg",
            "viewLabel": "Biển - Hạ Long Xanh",
            "position": 3
         },
         "25": {
            "code": "P1-06-25",
            "type": "Studio",
            "area": 31.29,
            "price": null,
            "floor": 7,
            "directionLabel": "Hướng Tây",
            "direction": "tay.jpg",
            "view": "bien-halongxanh.jpg",
            "viewLabel": "Biển - Hạ Long Xanh",
            "position": 3
         },
         "26": {
            "code": "P1-06-26",
            "type": "Studio",
            "area": 32.55,
            "price": null,
            "floor": 7,
            "directionLabel": "Hướng Tây",
            "direction": "tay.jpg",
            "view": "bien-halongxanh.jpg",
            "viewLabel": "Biển - Hạ Long Xanh",
            "position": 3
         }
      }
   },
   "P2": {
      "05": {
         "11": {
            "code": "P2-05-11",
            "type": "Studio",
            "area": 32.72,
            "price": "",
            "floor": 5,
            "directionLabel": "Hướng Đông Nam",
            "direction": "dong-nam.jpg",
            "view": "bien.jpg",
            "viewLabel": "Biển",
            "position": 1
         },
         "12": {
            "code": "P2-05-12",
            "type": "Studio",
            "area": 32.04,
            "price": "",
            "floor": 5,
            "directionLabel": "Hướng Đông Nam",
            "direction": "dong-nam.jpg",
            "view": "bien.jpg",
            "viewLabel": "Biển",
            "position": 1
         },
         "12A": {
            "code": "P2-05-12A",
            "type": "Studio",
            "area": 32.04,
            "price": "",
            "floor": 5,
            "directionLabel": "Hướng Đông Nam",
            "direction": "dong-nam.jpg",
            "view": "bien.jpg",
            "viewLabel": "Biển",
            "position": 1
         },
         "14": {
            "code": "P2-05-14",
            "type": "Studio",
            "area": 33.66,
            "price": "",
            "floor": 5,
            "directionLabel": "Hướng Tây",
            "direction": "tay.jpg",
            "view": "bien-halongxanh.jpg",
            "viewLabel": "Biển - Hạ Long Xanh",
            "position": 3
         },
         "15": {
            "code": "P2-05-15",
            "type": "Studio",
            "area": 32.32,
            "price": "",
            "floor": 5,
            "directionLabel": "Hướng Tây",
            "direction": "tay.jpg",
            "view": "bien-halongxanh.jpg",
            "viewLabel": "Biển - Hạ Long Xanh",
            "position": 3
         },
         "16": {
            "code": "P2-05-16",
            "type": "Studio",
            "area": 33.66,
            "price": "",
            "floor": 5,
            "directionLabel": "Hướng Tây",
            "direction": "tay.jpg",
            "view": "bien-halongxanh.jpg",
            "viewLabel": "Biển - Hạ Long Xanh",
            "position": 3
         },
         "17": {
            "code": "P2-05-17",
            "type": "Studio",
            "area": 37.58,
            "price": "",
            "floor": 5,
            "directionLabel": "Hướng Tây",
            "direction": "tay.jpg",
            "view": "bien-halongxanh.jpg",
            "viewLabel": "Biển - Hạ Long Xanh",
            "position": 3
         },
         "18": {
            "code": "P2-05-18",
            "type": "2PN",
            "area": 59.24,
            "price": "",
            "floor": 5,
            "directionLabel": "Hướng Tây",
            "direction": "tay.jpg",
            "view": "bien-halongxanh.jpg",
            "viewLabel": "Biển - Hạ Long Xanh",
            "position": 3
         },
         "19": {
            "code": "P2-05-19",
            "type": "Studio",
            "area": 32.37,
            "price": "",
            "floor": 5,
            "directionLabel": "Hướng Tây",
            "direction": "tay.jpg",
            "view": "bien-halongxanh.jpg",
            "viewLabel": "Biển - Hạ Long Xanh",
            "position": 3
         },
         "20": {
            "code": "P2-05-20",
            "type": "Studio",
            "area": 32.37,
            "price": "",
            "floor": 5,
            "directionLabel": "Hướng Tây",
            "direction": "tay.jpg",
            "view": "bien-halongxanh.jpg",
            "viewLabel": "Biển - Hạ Long Xanh",
            "position": 3
         },
         "21": {
            "code": "P2-05-21",
            "type": "2PN",
            "area": 101.1,
            "price": "",
            "floor": 5,
            "directionLabel": "Hướng Tây Bắc",
            "direction": "tay-bac.jpg",
            "view": "nui.jpg",
            "viewLabel": "Hoàng Quốc Việt - Núi",
            "position": 3
         }
      },
      "06": {
         "01": {
            "code": "P2-06-01",
            "type": "2PN",
            "area": 72.42,
            "price": "",
            "floor": 7,
            "directionLabel": "Hướng Nam - Đông Nam",
            "direction": "nam-dong-nam.jpg",
            "view": "bien-vinhhalong.jpg",
            "viewLabel": "Biển - Vịnh Hạ Long",
            "position": 1
         },
         "02": {
            "code": "P2-06-02",
            "type": "Studio",
            "area": 31.01,
            "price": "",
            "floor": 7,
            "directionLabel": "Hướng Nam",
            "direction": "nam.jpg",
            "view": "vinhhalong.jpg",
            "viewLabel": "Vịnh Hạ Long",
            "position": 1
         },
         "03": {
            "code": "P2-06-03",
            "type": "Studio",
            "area": 31.01,
            "price": "",
            "floor": 7,
            "directionLabel": "Hướng Nam",
            "direction": "nam.jpg",
            "view": "vinhhalong.jpg",
            "viewLabel": "Vịnh Hạ Long",
            "position": 1
         },
         "03A": {
            "code": "P2-06-03A",
            "type": "Studio",
            "area": 31.94,
            "price": "",
            "floor": 7,
            "directionLabel": "Hướng Nam",
            "direction": "nam.jpg",
            "view": "vinhhalong.jpg",
            "viewLabel": "Vịnh Hạ Long",
            "position": 1
         },
         "05": {
            "code": "P2-06-05",
            "type": "Studio",
            "area": 31.94,
            "price": "",
            "floor": 7,
            "directionLabel": "Hướng Nam",
            "direction": "nam.jpg",
            "view": "vinhhalong.jpg",
            "viewLabel": "Vịnh Hạ Long",
            "position": 1
         },
         "06": {
            "code": "P2-06-06",
            "type": "Studio",
            "area": 31.01,
            "price": "",
            "floor": 7,
            "directionLabel": "Hướng Nam",
            "direction": "nam.jpg",
            "view": "vinhhalong.jpg",
            "viewLabel": "Vịnh Hạ Long",
            "position": 1
         },
         "07": {
            "code": "P2-06-07",
            "type": "Studio",
            "area": 31.01,
            "price": "",
            "floor": 7,
            "directionLabel": "Hướng Nam",
            "direction": "nam.jpg",
            "view": "vinhhalong.jpg",
            "viewLabel": "Vịnh Hạ Long",
            "position": 1
         },
         "08": {
            "code": "P2-06-08",
            "type": "Studio",
            "area": 31.98,
            "price": "",
            "floor": 7,
            "directionLabel": "Hướng Nam",
            "direction": "nam.jpg",
            "view": "vinhhalong.jpg",
            "viewLabel": "Vịnh Hạ Long",
            "position": 1
         },
         "09": {
            "code": "P2-06-09",
            "type": "Studio",
            "area": 31.98,
            "price": "",
            "floor": 7,
            "directionLabel": "Hướng Nam",
            "direction": "nam.jpg",
            "view": "vinhhalong.jpg",
            "viewLabel": "Vịnh Hạ Long",
            "position": 1
         },
         "10": {
            "code": "P2-06-10",
            "type": "Studio+",
            "area": 44.46,
            "price": "",
            "floor": 7,
            "directionLabel": "Hướng Nam",
            "direction": "nam.jpg",
            "view": "vinhhalong.jpg",
            "viewLabel": "Vịnh Hạ Long",
            "position": 1
         },
         "11": {
            "code": "P2-06-11",
            "type": "Studio",
            "area": 31.91,
            "price": "",
            "floor": 7,
            "directionLabel": "Hướng Đông Nam",
            "direction": "dong-nam.jpg",
            "view": "bien.jpg",
            "viewLabel": "Biển",
            "position": 1
         },
         "12": {
            "code": "P2-06-12",
            "type": "Studio",
            "area": 30.97,
            "price": "",
            "floor": 7,
            "directionLabel": "Hướng Đông Nam",
            "direction": "dong-nam.jpg",
            "view": "bien.jpg",
            "viewLabel": "Biển",
            "position": 1
         },
         "12A": {
            "code": "P2-06-12A",
            "type": "Studio",
            "area": 30.97,
            "price": "",
            "floor": 7,
            "directionLabel": "Hướng Đông Nam",
            "direction": "dong-nam.jpg",
            "view": "bien.jpg",
            "viewLabel": "Biển",
            "position": 1
         },
         "14": {
            "code": "P2-06-14",
            "type": "Studio",
            "area": 32.55,
            "price": null,
            "floor": 7,
            "directionLabel": "Hướng Tây",
            "direction": "tay.jpg",
            "view": "bien-halongxanh.jpg",
            "viewLabel": "Biển - Hạ Long Xanh",
            "position": 3
         },
         "15": {
            "code": "P2-06-15",
            "type": "Studio",
            "area": 31.29,
            "price": null,
            "floor": 7,
            "directionLabel": "Hướng Tây",
            "direction": "tay.jpg",
            "view": "bien-halongxanh.jpg",
            "viewLabel": "Biển - Hạ Long Xanh",
            "position": 3
         },
         "16": {
            "code": "P2-06-16",
            "type": "Studio",
            "area": 32.26,
            "price": null,
            "floor": 7,
            "directionLabel": "Hướng Tây",
            "direction": "tay.jpg",
            "view": "bien-halongxanh.jpg",
            "viewLabel": "Biển - Hạ Long Xanh",
            "position": 3
         },
         "17": {
            "code": "P2-06-17",
            "type": "Studio",
            "area": 37.58,
            "price": null,
            "floor": 7,
            "directionLabel": "Hướng Tây",
            "direction": "tay.jpg",
            "view": "bien-halongxanh.jpg",
            "viewLabel": "Biển - Hạ Long Xanh",
            "position": 3
         },
         "18": {
            "code": "P2-06-18",
            "type": "2PN",
            "area": 59.17,
            "price": null,
            "floor": 7,
            "directionLabel": "Hướng Tây",
            "direction": "tay.jpg",
            "view": "bien-halongxanh.jpg",
            "viewLabel": "Biển - Hạ Long Xanh",
            "position": 3
         },
         "19": {
            "code": "P2-06-19",
            "type": "Studio",
            "area": 31.26,
            "price": null,
            "floor": 7,
            "directionLabel": "Hướng Tây",
            "direction": "tay.jpg",
            "view": "bien-halongxanh.jpg",
            "viewLabel": "Biển - Hạ Long Xanh",
            "position": 3
         },
         "20": {
            "code": "P2-06-20",
            "type": "Studio",
            "area": 31.26,
            "price": null,
            "floor": 7,
            "directionLabel": "Hướng Tây",
            "direction": "tay.jpg",
            "view": "bien-halongxanh.jpg",
            "viewLabel": "Biển - Hạ Long Xanh",
            "position": 3
         },
         "21": {
            "code": "P2-06-21",
            "type": "2PN",
            "area": 72.47,
            "price": null,
            "floor": 7,
            "directionLabel": "Hướng Tây Bắc",
            "direction": "tay-bac.jpg",
            "viewLabel": "Hoàng Quốc Việt - Núi",
            "view": "nui.jpg",
            "position": 3
         },
         "22": {
            "code": "P2-06-22",
            "type": "Studio",
            "area": 31.29,
            "price": null,
            "floor": 7,
            "directionLabel": "Hướng Bắc",
            "direction": "bac.jpg",
            "viewLabel": "Hoàng Quốc Việt - Núi",
            "view": "hoangquocviet-nui.jpg",
            "position": 2
         },
         "23": {
            "code": "P2-06-23",
            "type": "Studio",
            "area": 32.26,
            "price": null,
            "floor": 7,
            "directionLabel": "Hướng Bắc",
            "direction": "bac.jpg",
            "viewLabel": "Hoàng Quốc Việt - Núi",
            "view": "hoangquocviet-nui.jpg",
            "position": 2
         },
         "24": {
            "code": "P2-06-24",
            "type": "Studio",
            "area": 32.26,
            "price": null,
            "floor": 7,
            "directionLabel": "Hướng Bắc",
            "direction": "bac.jpg",
            "viewLabel": "Hoàng Quốc Việt - Núi",
            "view": "hoangquocviet-nui.jpg",
            "position": 2
         },
         "25": {
            "code": "P2-06-25",
            "type": "Studio",
            "area": 31.26,
            "price": null,
            "floor": 7,
            "directionLabel": "Hướng Bắc",
            "direction": "bac.jpg",
            "viewLabel": "Hoàng Quốc Việt - Núi",
            "view": "hoangquocviet-nui.jpg",
            "position": 2
         },
         "26": {
            "code": "P2-06-26",
            "type": "Studio",
            "area": 31.26,
            "price": null,
            "floor": 7,
            "directionLabel": "Hướng Bắc",
            "direction": "bac.jpg",
            "viewLabel": "Hoàng Quốc Việt - Núi",
            "view": "hoangquocviet-nui.jpg",
            "position": 2
         },
         "27": {
            "code": "P2-06-27",
            "type": "Studio",
            "area": 31.29,
            "price": null,
            "floor": 7,
            "directionLabel": "Hướng Bắc",
            "direction": "bac.jpg",
            "viewLabel": "Hoàng Quốc Việt - Núi",
            "view": "hoangquocviet-nui.jpg",
            "position": 2
         },
         "28": {
            "code": "P2-06-28",
            "type": "Studio",
            "area": 31.29,
            "price": null,
            "floor": 7,
            "directionLabel": "Hướng Bắc",
            "direction": "bac.jpg",
            "viewLabel": "Hoàng Quốc Việt - Núi",
            "view": "hoangquocviet-nui.jpg",
            "position": 2
         },
         "29": {
            "code": "P2-06-29",
            "type": "Studio",
            "area": 32.26,
            "price": null,
            "floor": 7,
            "directionLabel": "Hướng Bắc",
            "direction": "bac.jpg",
            "viewLabel": "Hoàng Quốc Việt - Núi",
            "view": "hoangquocviet-nui.jpg",
            "position": 2
         },
         "30": {
            "code": "P2-06-30",
            "type": "Studio",
            "area": 33.66,
            "price": null,
            "floor": 7,
            "directionLabel": "Hướng Bắc",
            "direction": "bac.jpg",
            "viewLabel": "Hoàng Quốc Việt - Núi",
            "view": "hoangquocviet-nui.jpg",
            "position": 2
         },
         "31": {
            "code": "P2-06-31",
            "type": "Studio",
            "area": 32.85,
            "price": null,
            "floor": 7,
            "directionLabel": "Hướng Bắc",
            "direction": "bac.jpg",
            "viewLabel": "Hoàng Quốc Việt - Núi",
            "view": "hoangquocviet-nui.jpg",
            "position": 2
         },
         "32": {
            "code": "P2-06-32",
            "type": "Studio",
            "area": 31.29,
            "price": null,
            "floor": 7,
            "directionLabel": "Hướng Bắc",
            "direction": "bac.jpg",
            "viewLabel": "Hoàng Quốc Việt - Núi",
            "view": "hoangquocviet-nui.jpg",
            "position": 2
         },
         "33": {
            "code": "P2-06-33",
            "type": "Studio",
            "area": 31.30,
            "price": null,
            "floor": 7,
            "directionLabel": "Hướng Bắc",
            "direction": "bac.jpg",
            "viewLabel": "Hoàng Quốc Việt - Núi",
            "view": "hoangquocviet-nui.jpg",
            "position": 2
         },
         "34": {
            "code": "P2-06-34",
            "type": "2PN",
            "area": 72.41,
            "price": null,
            "floor": 7,
            "directionLabel": "Hướng Bắc",
            "direction": "bac.jpg",
            "viewLabel": "Núi",
            "view": "nui.jpg",
            "position": 2
         }
      }
   }
}

